# Используем базовый образ Python 3
FROM python:3.9-slim

# Устанавливаем рабочую директорию
WORKDIR /usr/src/app

# Копируем Python-скрипт
COPY script.py .

# Указываем команду по умолчанию
CMD ["python3", "script.py"]
